-- ============================================================
-- 私房菜谱 Supabase 建表 SQL
-- 在 Supabase Dashboard → SQL Editor 中执行
-- ============================================================

-- 1. 创建 recipes 表
CREATE TABLE IF NOT EXISTS public.recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT '家常菜',
  subcategory TEXT DEFAULT '其他',
  tags TEXT[] DEFAULT '{}',
  difficulty TEXT DEFAULT '中等',
  "cookingTime" INTEGER DEFAULT 30,
  servings TEXT DEFAULT '2-3人份',
  ingredients JSONB DEFAULT '[]',
  steps JSONB DEFAULT '[]',
  tips TEXT[] DEFAULT '{}',
  nutrition TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 启用 RLS（行级安全）
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;

-- 3. 允许匿名用户读取（公开读取）
CREATE POLICY "允许公开读取" ON public.recipes
  FOR SELECT USING (true);

-- 4. 允许匿名用户写入（新增/修改/删除）
-- ⚠️ 生产环境建议改为仅认证用户可写
CREATE POLICY "允许公开写入" ON public.recipes
  FOR INSERT WITH CHECK (true);

CREATE POLICY "允许公开更新" ON public.recipes
  FOR UPDATE USING (true);

CREATE POLICY "允许公开删除" ON public.recipes
  FOR DELETE USING (true);

-- 5. 创建索引
CREATE INDEX IF NOT EXISTS idx_recipes_category ON public.recipes(category);
CREATE INDEX IF NOT EXISTS idx_recipes_subcategory ON public.recipes(subcategory);

-- 6. 导入现有数据（可选）
-- 此步骤可通过 Supabase 的 Import 功能导入 recipes_full.json
-- 或取消注释下面的 INSERT 语句手动逐条导入